# Generated by Django 5.0.3 on 2024-09-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('tenth_per', models.IntegerField()),
                ('twelve_per', models.IntegerField()),
                ('interest_dept', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
